### ISSUE TITLE
Library not loaded: @loader_path/libmex.dylib error in MacOS matlab 2017

### ISSUE THREAD

**Issue by sari-saba-sadiya** [justingardner/mgl#34] opened 2021-01-25 04:19 UTC
Hi,

I am running on macOs high sierra 10.13.9 with xcode 9 and matlab 2017b. This specific setup is necessary as I am using openBCI which does not work well with previous versions.

When running initscreen I get the error:
`
Invalid MEX-file '/Users/admin/apps/mgl/mgllib/mglResolution.mexmaci64':
dlopen(/Users/admin/apps/mgl/mgllib/mglResolution.mexmaci64, 6): Library not
loaded: @loader_path/libmex.dylib
`

I tried to recompile using `mglMake` however I then get the error `Error using mex mexopts.10.5.sh is not a valid XML file.`

I believe that the both errors originate from the things having changed between recent matlab versions. This suspicion is supported by the fact that the same code ran fine with macOS El Capitan 10.11 and matlab 2015.

A day of googling did not yield any results, updating the `DYLD_LIBRARY_PATH` and trying to recompile.

Any guidance would be greatly appreciated.

Thank you very much!

**Comment by justingardner** [comment] 2021-01-28 00:53
Hi Sari,

Yes, this looks like you need to recompile. You are probably right that the problem is Matlab version as they keep changing how compilation flags work. You might try downloading the 2015a version of Matlab and seeing if you can compile with that.

Justin
=====================================================
Justin L. Gardner, PhD
Assistant Professor, Department of Psychology, Stanford University
450-420 Jane Stanford Way, Stanford CA 94305
https://gru.stanford.edu
=====================================================

**Comment by justingardner** [comment] 2022-04-06 03:22
Closing out - we are working on a new version of metal (based on metal) with new compilation scripts mglMakeMetal this will be the new default version of mgl for newer systems / matlab versions / OS versions

**Closed by justingardner** 2022-04-06 03:22 UTC
